# Generated by Django 2.1.7 on 2019-03-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('number_of_delays', models.IntegerField(default=0)),
                ('delays_total', models.IntegerField(default=0)),
                ('cancellations_Rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_rating', to='api.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_review', to='api.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_descriptive_statistics', to='api.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_entries', to='api.Airport')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_entries', to='api.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled', models.IntegerField()),
                ('delayed', models.IntegerField()),
                ('diverted', models.IntegerField()),
                ('on_time', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MinutesDelayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.IntegerField()),
                ('late_aircraft', models.IntegerField()),
                ('national_aviation_system', models.IntegerField()),
                ('security', models.IntegerField()),
                ('total', models.IntegerField()),
                ('weather', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfDelays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.IntegerField()),
                ('late_aircraft', models.IntegerField()),
                ('national_aviation_system', models.IntegerField()),
                ('security', models.IntegerField()),
                ('weather', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flights_statistics', to='api.Flights')),
                ('minutes_delayed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_delayed_statistics', to='api.MinutesDelayed')),
                ('number_of_delays', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_of_delays_statistics', to='api.NumberOfDelays')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_entry', to='api.Statistics'),
        ),
        migrations.AddField(
            model_name='entry',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_time', to='api.Time'),
        ),
    ]
