# Generated by Django 2.1.7 on 2019-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='cancellations_Rate',
            new_name='cancellations_rate',
        ),
        migrations.AddField(
            model_name='carrier',
            name='number_of_cancellations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='total_flights',
            field=models.IntegerField(default=0),
        ),
    ]
