# Generated by Django 2.1.7 on 2019-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190319_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='cancellations_rate',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='delays_total',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='number_of_cancellations',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='number_of_delays',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='total_flights',
        ),
    ]
